- name: Copy config file
  copy:
    src: "{{playbook_dir}}/roles/dnf/files/dnf.conf"
    dest: /etc/dnf
  become: yes

- name: Set permissions
  ansible.builtin.file:
    path: /etc/dnf/dnf.conf
    mode: '0640'
  become: yes