- name: Setup SSH key for server
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    size: 4096
    comment: "tandy@local"

- name: Copy SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: tandy
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become: yes