- name: Setup tandy SSH key for server
  community.crypto.openssh_keypair:
    path: ~/.ssh/tandy_id_rsa
    size: 4096
    comment: "tandy@server.local"

- name: Copy tandy SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: tandy
    state: present
    key: "{{ lookup('file', '~/.ssh/tandy_id_rsa.pub') }}"
  become: yes

- name: Setup borg SSH key for server
  community.crypto.openssh_keypair:
    path: ~/.ssh/borg_id_rsa
    size: 4096
    comment: "borg@server.local"

- name: Copy borg SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: borg
    state: present
    key: "{{ lookup('file', '~/.ssh/borg_id_rsa.pub') }}"
  become: yes