- name: "Setup {{ ansible_user }} SSH key for server"
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/{{ ansible_user }}_id_rsa"
    size: 4096
    comment: "{{ ansible_user }}@server.local"

- name: "Copy {{ ansible_user }} SSH key"
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/{{ ansible_user }}_id_rsa.pub') }}"
  become: yes

- name: Setup borg SSH key for server
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/borg_id_rsa"
    size: 4096
    comment: "borg@server.local"

- name: Copy borg SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: borg
    state: present
    key: "{{ lookup('file', '/home/{{ ansible_user }}/.ssh/borg_id_rsa.pub') }}"
  become: yes