- name: Setup btrbk SSH key
  community.crypto.openssh_keypair:
    path: /etc/btrbk/ssh/id_rsa
    size: 4096
    comment: "btrbk@server.local"

- name: Copy btrbk SSH key
  delegate_to: server.local
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/etc/btrbk/ssh/id_rsa.pub') }}"
  become: yes

- name: Copy config file
  copy:
    src: "{{playbook_dir}}/roles/btrbk/files/btrbk.conf"
    dest: /etc/btrbk
    mode: '0640'
  become: yes