- name: Copy config file
  copy:
    src: "{{ playbook_dir }}/roles/snapper/files/root"
    dest: /etc/snapper/configs/
  become: yes

- name: Set permissions
  file:
    path: /etc/snapper/configs/root
    mode: '0640'
  become: yes

- name: Enable cleanup
  systemd:
    enabled: yes
    name: snapper-cleanup.timer
  become: yes

- name: Enable user access
  file:
    path: /.snapshots
    state: directory
    mode: 'a+rx'
    group: "{{ ansible_user }}"
  become: yes
