- name: Add the Flathub remoate
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    name:
      - org.signal.Signal
      - com.borgbase.Vorta
      - com.github.alainm23.planner
      - com.bitwarden.desktop
      - net.cozic.joplin_desktop