- include_tasks: nim.yml

- include_tasks: flatpak.yml

- include_tasks: vscodium.yml

- name: Add RPM Fusion repo key
  rpm_key:
    state: present
    key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
  become: yes

- name: Enable the RPM Fusion repo
  package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
  become: yes

- name: Install DNF packages
  package:
    name:
      - thunderbird
      - codium
      - yt-dlp
      - gimp
      - lollypop
      - vlc
      - syncthing
      - evolution-data-server
      - wireguard-tools
      - btrbk
      - python3-dnf-plugin-snapper
      - borgbackup
    state: present
  become: yes