- name: Clone gitnim
  git:
    repo: https://github.com/nim-works/gitnim/
    dest: "/home/{{ ansible_user }}/.gitnim"

- name: Add gitnim to PATH
  shell:
    echo 'export PATH=/home/{{ ansible_user }}/.gitnim/bin:$PATH' >> /home/{{ ansible_user }}/.bash_profile

- name: Update PATH
  shell:
    source "/home/{{ ansible_user }}/.bash_profile"

- name: Build gitnim
  command:
    cmd: nim c gitnim/gitnim.nim
    chdir: "/home/{{ ansible_user }}/.gitnim"

- name: Setup Nim devel
  raw: git nim -q devel