- name: Download choosenim
  get_url:
    url: https://nim-lang.org/choosenim/init.sh
    dest: /tmp/choosenim.sh
    mode: +x

- name: Install choosenim
  shell:
    /tmp/choosenim.sh -y

- name: Setup Nim devel
  shell:
    choosenim devel