- name: Clone gitnim
  git:
    repo: https://github.com/nim-works/gitnim/
    dest: ~/.gitnim

- name: Add gitnim to $PATH
  shell:
    echo "PATH=/home/tandy/.gitnim/bin:$PATH" >> ~/.bash_profile

- name: Build gitnim
  shell:
    command: nim c gitnim/gitnim.nim
    chdir: ~/.gitnim

- name: Setup Nim devel
  shell:
    git nim devel
