- name: Add VSCodium repo key
  rpm_key:
    state: present
    key: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg
  become: yes

- name: Copy VSCodium repo file
  copy:
    src: "{{ playbook_dir }}/roles/install/files/vscodium.repo"
    dest: /etc/yum.repos.d/
    mode: '0640'
  become: yes
